apiVersion:  v1
kind: Secret
metadata:
  name: k8s-tutorial-secrets
  labels:
    eidf/user: cwheeler-eidf220
type: Opaque
stringData:
  wandb-api-key: <add your api key here, I am not doing that here as I am checking this code in ;)>